# Generated by Django 4.1.4 on 2022-12-20 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=255)),
                ('pro_img', models.ImageField(null=True, upload_to='')),
                ('pro_size', models.CharField(max_length=10)),
                ('pro_material', models.CharField(max_length=10)),
                ('pro_price', models.IntegerField()),
                ('pro_quantity', models.IntegerField()),
                ('pro_desc', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.categories')),
            ],
        ),
    ]
