# Generated by Django 4.1.4 on 2022-12-26 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_customer_options_alter_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'customer', 'verbose_name_plural': 'Customers'},
        ),
    ]
