# Generated by Django 4.1.4 on 2022-12-26 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_customer_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
