# Generated by Django 4.1.4 on 2022-12-26 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_categories_category_rename_products_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'customer', 'verbose_name_plural': 'customers'},
        ),
    ]
