# Generated by Django 4.1.4 on 2022-12-26 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_customer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'customer', 'verbose_name_plural': 'customer'},
        ),
    ]
