# Generated by Django 4.1.4 on 2022-12-26 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_cart_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'verbose_name': 'shippingaddress', 'verbose_name_plural': 'Shipping Address'},
        ),
    ]
