# Generated by Django 4.1.4 on 2022-12-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_shippingaddress_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_name',
            field=models.CharField(max_length=255, verbose_name='name list'),
        ),
    ]
