# Generated by Django 4.1.4 on 2022-12-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_delete_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_img',
            field=models.ImageField(null=True, upload_to='', verbose_name='image'),
        ),
    ]
