# Generated by Django 4.1.4 on 2022-12-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_category_cat_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='address',
            field=models.CharField(max_length=255, verbose_name='address'),
        ),
    ]
