# Generated by Django 4.1.4 on 2022-12-26 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_product_pro_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pro_desc',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pro_img',
            field=models.ImageField(null=True, upload_to='', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pro_material',
            field=models.CharField(max_length=10, verbose_name='material'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pro_price',
            field=models.IntegerField(verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pro_quantity',
            field=models.IntegerField(verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pro_size',
            field=models.CharField(max_length=10, verbose_name='size'),
        ),
    ]
